### ISSUE TITLE
GZFileStream atEnd too late

### ISSUE THREAD

**Issue by blaiseli** [nim-lang/zip#26]
I have a file with 8 lines that I compress with gzip:
```
bli@naples:~/src/bioinfo_utils/fastq-demultiplexing/Nim$ cat test8lines.txt
1
2
3
4
5
6
7
8
bli@naples:~/src/bioinfo_utils/fastq-demultiplexing/Nim$ gzip -k test8lines.txt
```

The following program parses the files four lines by four lines and prints something made with the lines:

```nim
from streams import newFileStream, Stream, atEnd, readLine
from zip/gzipfiles import newGZFileStream

from strutils import join

proc fourLineParser(stream: Stream): iterator(): tuple[one: string, two: string, three: string, four: string] =
  result = iterator(): tuple[one: string, two: string, three: string, four: string] =
    var
      lineOne: string
      lineTwo: string
      lineThree: string
      lineFour: string
    while not stream.atEnd():
      lineOne = stream.readLine()
      lineTwo = stream.readLine()
      lineThree = stream.readLine()
      lineFour = stream.readLine()
      yield (lineOne, lineTwo, lineThree, lineFour)

let normalInput = fourLineParser(newFileStream("test8lines.txt"))
for l1, l2, l3, l4 in normalInput():
  echo join([l1, l2, l3, l4], " ")

let gzInput = fourLineParser(newGZFileStream("test8lines.txt.gz"))
for l1, l2, l3, l4 in gzInput():
  echo join([l1, l2, l3, l4], " ")
```

The program outputs an extra empty line in the second case:
```
bli@naples:~/src/bioinfo_utils/fastq-demultiplexing/Nim$ nim c -r testgz.nim                                                     
Hint: used config file '/home/bli/src/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: testgz [Processing]
Hint: streams [Processing]
Hint: gzipfiles [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: ospaths [Processing]
Hint: zlib [Processing]
Hint:  [Link]
Hint: operation successful (23642 lines compiled; 0.420 sec total; 54.746MiB peakmem; Debug Build) [SuccessX]
Hint: /home/bli/src/bioinfo_utils/fastq-demultiplexing/Nim/testgz  [Exec]
1 2 3 4
5 6 7 8
1 2 3 4
5 6 7 8
   
bli@naples:~/src/bioinfo_utils/fastq-demultiplexing/Nim$
```

I expect the output to be the same as when processing a stream made from the non compressed file.

**Comment by dom96** [comment]
Seems like maybe one is adding a trailing new line and the other isn't?

**Comment by recloser** [comment]
This happens because the stdlib `FileStream`'s `atEnd` peeks to check for EOF, whereas `GzFileStream`'s one uses `gzeof` which checks for a flag set _after_ a failed read. To make `GzFileStream`'s behavior consistent with `FileStream` I had to change types on some procs in the interface module, since they were incorrect. I'm guessing this calls for upping the version?

**Comment by dom96** [comment]
Yep :)

**Comment by dom96** [comment]
Thank you for fixing this!

**Comment by recloser** [comment]
I wanted to make a PR for this, but then I realized that the `zlib.nim` wrapper has wrong types in a ton of places! E.g. it aliases `Ulong` as `int`, but in [`zlib.h`](https://github.com/madler/zlib/blob/master/zlib.h) it's, unsurprisingly, typedef'd to `unsigned long`, it uses as `int` instead of `cuint` for the length for `gzread` and `gzwrite`, etc. Also, the code uses `int32` all over the place, but I suppose it technically should be using `cint`s. 
I guess I should make a new issue and all that should be fixed up, but should include it all in one PR or split it?

**Comment by Araq** [comment]
Most of these typing issues are OK in my book for reasons I don't want to go into, but sure fix them in a separate PR.
